export const kabupatenBogor = [
  "Babakan Madang",
  "Bojonggede",
  "Cariu",
  "Ciampea",
  "Cibinong",
  "Cisarua",
  "Citeureup",
  "Dramaga",
  "Gunung Putri",
  "Gunung Sindur",
  "Jasinga",
  "Jonggol",
  "Kemang",
  "Klapanunggal",
  "Leuwiliang",
  "Leuwisadeng",
  "Megamendung",
  "Nanggung",
  "Pamijahan",
  "Parung",
  "Parung Panjang",
  "Rancabungur",
  "Sukajaya",
  "Sukamakmur",
  "Sukaraja",
  "Tajurhalang",
  "Tamansari",
  "Tanjungsari",
  "Tenjo",
  "Tenjolaya",
  "Cigombong",
  "Cigudeg",
  "Cijeruk",
  "Cileungsi",
  "Ciomas",
  "Cibungbulang",
  "Cihideung",
  "Ciseeng",
  "Kelapa Nunggal",
  "Rumpin",
];
